// alunos/malu/template-frontend-react/src/pages/home/delete-vehicle-modal/index.tsx
import { Button } from '@/components/button'
import { Modal } from '@/components/modal'
import { vehicleService } from '@/services/vehicles'
import type { Vehicle } from '@/types/vehicle'

type Props = {
  vehicle?: Vehicle | null
  isOpen: boolean
  onClose: () => void
  onReload?: () => void
}

export function DeleteVehicleModal({
  vehicle,
  isOpen,
  onClose,
  onReload,
}: Props) {
  const handleConfirm = async () => {
    if (!vehicle) return
    try {
      await vehicleService.delete.execute(vehicle.id)

      onClose()
      onReload?.()
    } catch (error: any) {
      alert(error?.message || 'Algo deu errado')
    }
  }

  const vehicleDescription = vehicle ? (
    <>
      o veículo{' '}
      <strong>
        {vehicle.chassi} ({vehicle.brand} {vehicle.model} {vehicle.year})
      </strong>
    </>
  ) : (
    'este livro'
  )

  return (
    <Modal title="Excluir livro" isOpen={isOpen} onClose={onClose}>
      <p style={{ lineHeight: 1.4 }}>
        Tem certeza de que deseja excluir {vehicleDescription}? Essa ação não
        poderá ser desfeita.
      </p>

      <div
        style={{
          display: 'flex',
          justifyContent: 'flex-end',
          gap: 16,
          marginTop: 16,
        }}
      >
        <Button onClick={onClose}>Cancelar</Button>
        <Button onClick={handleConfirm}>Confirmar</Button>
      </div>
    </Modal>
  )
}

// aulas/aula9-frameworks/template-frontend-vue/src/views/home/delete-vehicle-modal/DeleteVehicleModal.vue
<script setup lang="ts">
import { computed } from 'vue'
import Button from '@/components/button/Button.vue'
import Modal from '@/components/modal/Modal.vue'
import { vehicleService } from '@/services/vehicles'
import type { Vehicle } from '@/types/vehicle'

interface Props {
  vehicle?: Vehicle | null
  isOpen: boolean
}

const props = defineProps<Props>()
const emit = defineEmits<{
  (e: 'close'): void
  (e: 'reload'): void
}>()

const handleConfirm = async () => {
  if (!props.vehicle) return
  try {
    await vehicleService.delete.execute(props.vehicle.id)
    emit('close')
    emit('reload')
  } catch (error: any) {
    alert(error?.message || 'Algo deu errado')
  }
}

const vehicleDescriptionPrefix = computed(() => {
  const v = props.vehicle
  return v ? 'o veículo' : 'este veículo'
})
const vehicleDescription = computed(() => {
  const v = props.vehicle
  return v ? ` ${v.chassi} (${v.brand} ${v.model} ${v.year})` : ''
})
</script>

<template>
  <Modal title="Excluir Veículo" :is-open="isOpen" @close="emit('close')">
    <p style="line-height: 1.4">
      Tem certeza de que deseja excluir {{ vehicleDescriptionPrefix
      }}<strong>{{ vehicleDescription }}</strong
      >? Essa ação não poderá ser desfeita.
    </p>

    <div style="display: flex; justify-content: flex-end; gap: 16px; margin-top: 16px">
      <Button @click="emit('close')">Cancelar</Button>
      <Button @click="handleConfirm">Confirmar</Button>
    </div>
  </Modal>
</template>
