// aulas/aula9-frameworks/template-frontend-angular/src/app/pages/home/home.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ButtonComponent } from '@/app/components/button/button.component';
import { CreateVehicleModalComponent } from './create-vehicle-modal/modal.component';
import { EditVehicleModalComponent } from './edit-vehicle-modal/modal.component';
import { DeleteVehicleModalComponent } from './delete-vehicle-modal/modal.component';
import { vehicleService } from '@/services/vehicles';
import type { Vehicle } from '@/types/vehicle';

@Component({
  selector: 'app-home-page',
  standalone: true,
  imports: [
    CommonModule,
    ButtonComponent,
    CreateVehicleModalComponent,
    EditVehicleModalComponent,
    DeleteVehicleModalComponent,
  ],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomePage {
  vehicles: Vehicle[] = [];
  isCreateModalOpen = false;
  vehicleToEdit: number | null = null;
  vehicleToDelete: Vehicle | null = null;

  async ngOnInit() {
    await this.handleFetchVehicles();
  }

  async handleFetchVehicles() {
    try {
      this.vehicles = await vehicleService.get.execute();
    } catch (error: any) {
      alert(error?.message || 'Algo deu errado');
    }
  }

  handleReload() {
    this.handleFetchVehicles();
  }

  openCreateModal() {
    this.isCreateModalOpen = true;
  }

  closeCreateModal() {
    this.isCreateModalOpen = false;
  }

  selectVehicleToEdit(id: number) {
    this.vehicleToEdit = id;
  }

  closeEditModal() {
    this.vehicleToEdit = null;
  }

  selectVehicleToDelete(vehicle: Vehicle) {
    this.vehicleToDelete = vehicle;
  }

  closeDeleteModal() {
    this.vehicleToDelete = null;
  }
}

<div class="homePage">
  <div class="header">
    <h1>Lista de Veículos</h1>
    <app-button (click)="openCreateModal()">Novo veículo</app-button>
  </div>

  <ng-container *ngIf="vehicles.length; else emptyList">
    <table border="1">
      <thead>
        <tr>
          <th>Chassi</th>
          <th>Marca</th>
          <th>Modelo</th>
          <th>Ano</th>
          <th class="actionsHeader">Ações</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let vehicle of vehicles">
          <td>{{ vehicle.chassi | uppercase }}</td>
          <td>{{ vehicle.brand }}</td>
          <td>{{ vehicle.model }}</td>
          <td>{{ vehicle.year }}</td>
          <td class="actions">
            <app-button size="sm" (click)="selectVehicleToEdit(vehicle.id)"> Editar </app-button>
            <app-button size="sm" (click)="selectVehicleToDelete(vehicle)"> Excluir </app-button>
          </td>
        </tr>
      </tbody>
    </table>
  </ng-container>

  <ng-template #emptyList>
    <div class="emptyList">
      <p>Não há veículos cadastrados</p>
    </div>
  </ng-template>

  <app-create-vehicle-modal
    [isOpen]="isCreateModalOpen"
    (onClose)="closeCreateModal()"
    (onReload)="handleReload()"
  ></app-create-vehicle-modal>

  <app-edit-vehicle-modal
    [isOpen]="!!vehicleToEdit"
    [id]="vehicleToEdit"
    (onClose)="closeEditModal()"
    (onReload)="handleReload()"
  ></app-edit-vehicle-modal>

  <app-delete-vehicle-modal
    [isOpen]="!!vehicleToDelete"
    [vehicle]="vehicleToDelete"
    (onClose)="closeDeleteModal()"
    (onReload)="handleReload()"
  ></app-delete-vehicle-modal>
</div>

// alunos/malu/template-frontend-react/src/pages/home/index.tsx
import { useEffect, useState } from 'react'
import { Button } from '@/components/button'
import { vehicleService } from '@/services/vehicles'
import type { Vehicle } from '@/types/vehicle'
import { CreateVehicleModal } from './create-vehicle-modal'
import { DeleteVehicleModal } from './delete-vehicle-modal'
import { EditVehicleModal } from './edit-vehicle-modal'
import styles from './styles.module.css'

export function HomePage() {
  const [vehicles, setVehicles] = useState<Vehicle[]>([])
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false)
  const [vehicleToEdit, setVehicleToEdit] = useState<number | null>(null)
  const [vehicleToDelete, setVehicleToDelete] = useState<Vehicle | null>(null)
  const [reload, setReload] = useState(Date.now())

  const handleFetchVehicles = async () => {
    try {
      const response = await vehicleService.get.execute()
      setVehicles(response)
    } catch (error: any) {
      alert(error?.message || 'Algo deu errado')
    }
  }

  useEffect(() => {
    handleFetchVehicles()
  }, [reload])

  return (
    <div className={styles.homePage}>
      <div className={styles.header}>
        <h1>Lista de Veículos</h1>

        <Button onClick={() => setIsCreateModalOpen(true)}>Novo veículo</Button>
      </div>

      {vehicles.length ? (
        <table border={1}>
          <thead>
            <tr>
              <th>Código</th>
              <th>Título</th>
              <th>Escritor</th>
              <th>Lançamento</th>
              <th className={styles.actionsHeader}>Ações</th>
            </tr>
          </thead>
          <tbody>
            {vehicles.map((vehicle) => (
              <tr key={vehicle.chassi}>
                <td>{vehicle.chassi.toUpperCase()}</td>
                <td>{vehicle.brand}</td>
                <td>{vehicle.model}</td>
                <td>{vehicle.year}</td>
                <td className={styles.actions}>
                  <Button
                    size="sm"
                    onClick={() => setVehicleToEdit(vehicle.id)}
                  >
                    Editar
                  </Button>
                  <Button size="sm" onClick={() => setVehicleToDelete(vehicle)}>
                    Excluir
                  </Button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      ) : (
        <div className={styles.emptyList}>
          <p>Não há veículos cadastrados</p>
        </div>
      )}

      <CreateVehicleModal
        isOpen={isCreateModalOpen}
        onClose={() => setIsCreateModalOpen(false)}
        onReload={() => setReload(Date.now())}
      />
      <EditVehicleModal
        isOpen={!!vehicleToEdit}
        onClose={() => setVehicleToEdit(null)}
        onReload={() => setReload(Date.now())}
        id={vehicleToEdit}
      />
      <DeleteVehicleModal
        isOpen={!!vehicleToDelete}
        onClose={() => setVehicleToDelete(null)}
        onReload={() => setReload(Date.now())}
        vehicle={vehicleToDelete}
      />
    </div>
  )
}
